name: Auto Deploy After PR Approval

on:
  pull_request:
    types: [closed]
  push:
    branches: [ main ]

env:
  PROJECT_ID: gen-lang-client-0502058841

jobs:
  # Deploy when MarioH88 merges PR or pushes directly to main
  deploy:
    runs-on: ubuntu-latest
    # Deploy on any push to main by MarioH88 (simplified condition)
    if: github.event_name == 'push' && github.actor == 'MarioH88'
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Deploy Info
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "AUTO-DEPLOY: Direct push by @MarioH88"
          else
            echo "AUTO-DEPLOY: PR approved and merged by @MarioH88"
            echo "PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
            echo "Author: @${{ github.event.pull_request.user.login }}"
          fi
          echo "Deploying to: https://devops-backup-1002595611169.europe-west1.run.app"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy with Cloud Build
        run: |
          gcloud builds submit --config=cloudbuild.yaml --project=${{ env.PROJECT_ID }}

      - name: Deployment Success
        run: |
          echo "DEPLOYMENT COMPLETED"
          echo "URL: https://devops-backup-1002595611169.europe-west1.run.app"
          echo "Your app is now updated!"