name: PR Approval Required

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  require-approval:
    runs-on: ubuntu-latest
    if: github.actor != 'MarioH88'
    steps:
      - name: Block Auto-Merge
        run: |
          echo "❌ APPROVAL REQUIRED: Only @MarioH88 can approve merges"
          echo "This PR must be manually approved by the repository owner"
          exit 1