name: Branch Protection

on:
  push:
    branches: [ main ]

jobs:
  # Block non-owners from direct pushes
  branch-protection:
    runs-on: ubuntu-latest
    if: github.actor != 'MarioH88'
    steps:
      - name: Block Unauthorized Direct Push
        run: |
          echo "🚨 BLOCKED: Direct push to main not allowed"
          echo "User: ${{ github.actor }}"
          echo ""
          echo "📋 Please use Pull Request workflow:"
          echo "1. Create a feature branch"
          echo "2. Submit a Pull Request"
          echo "3. Wait for @MarioH88 approval"
          echo "4. Auto-deploy after approval"
          exit 1